In [61]:
import pandas as pd
import numpy as np

In [63]:
# Create Academic Performance Dataset

data = {
    'Name': ['Amit', 'Riya', 'Karan', 'Sneha', 'Rahul',
             'Pooja', 'Vikas', 'Neha', 'Arjun', 'Priya'],
    
    'Maths': [85, 90, np.nan, 45, 120,
              78, 88, 92, 35, 80],
    
    'Science': [80, 85, 70, np.nan, 95,
                76, 89, 91, 40, 84],
    
    'English': [78, 88, 65, 50, 98,
                74, 90, 93, 42, -5],
    
    'Attendance': [90, 95, 85, 60, 110,
                   80, 88, np.nan, 55, 92]
}

df = pd.DataFrame(data)

print("Original Dataset:\n")
df

Original Dataset:

    Name  Maths  Science  English  Attendance
0   Amit   85.0     80.0       78        90.0
1   Riya   90.0     85.0       88        95.0
2  Karan    NaN     70.0       65        85.0
3  Sneha   45.0      NaN       50        60.0
4  Rahul  120.0     95.0       98       110.0
5  Pooja   78.0     76.0       74        80.0
6  Vikas   88.0     89.0       90        88.0
7   Neha   92.0     91.0       93         NaN
8  Arjun   35.0     40.0       42        55.0
9  Priya   80.0     84.0       -5        92.0

In [65]:
df.isnull().sum()

Name          0
Maths         1
Science       1
English       0
Attendance    1
dtype: int64

In [67]:
df['Maths'].fillna(df['Maths'].mean(), inplace=True)

C:\Users\Prajwal\AppData\Local\Temp\ipykernel_48152\1425095364.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Maths'].fillna(df['Maths'].mean(), inplace=True)

In [69]:
df.isnull().sum()

Name          0
Maths         0
Science       1
English       0
Attendance    1
dtype: int64

In [71]:
df['Science'].fillna(df['Science'].mean(), inplace=True)

C:\Users\Prajwal\AppData\Local\Temp\ipykernel_48152\2374971838.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Science'].fillna(df['Science'].mean(), inplace=True)

In [73]:
df['Attendance'].fillna(df['Attendance'].mean(), inplace=True)

C:\Users\Prajwal\AppData\Local\Temp\ipykernel_48152\2424022987.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Attendance'].fillna(df['Attendance'].mean(), inplace=True)

In [75]:
df

    Name       Maths    Science  English  Attendance
0   Amit   85.000000  80.000000       78   90.000000
1   Riya   90.000000  85.000000       88   95.000000
2  Karan   79.222222  70.000000       65   85.000000
3  Sneha   45.000000  78.888889       50   60.000000
4  Rahul  120.000000  95.000000       98  110.000000
5  Pooja   78.000000  76.000000       74   80.000000
6  Vikas   88.000000  89.000000       90   88.000000
7   Neha   92.000000  91.000000       93   83.888889
8  Arjun   35.000000  40.000000       42   55.000000
9  Priya   80.000000  84.000000       -5   92.000000

In [77]:
# Handle inconsistencies

# Marks and attendance should be between 0 and 100

df['Maths'] = df['Maths'].clip(0, 100)

df['English'] = df['English'].clip(0, 100)

df['Attendance'] = df['Attendance'].clip(0, 100)

print("Dataset after removing inconsistencies:\n")

df

Dataset after removing inconsistencies:

    Name       Maths    Science  English  Attendance
0   Amit   85.000000  80.000000       78   90.000000
1   Riya   90.000000  85.000000       88   95.000000
2  Karan   79.222222  70.000000       65   85.000000
3  Sneha   45.000000  78.888889       50   60.000000
4  Rahul  100.000000  95.000000       98  100.000000
5  Pooja   78.000000  76.000000       74   80.000000
6  Vikas   88.000000  89.000000       90   88.000000
7   Neha   92.000000  91.000000       93   83.888889
8  Arjun   35.000000  40.000000       42   55.000000
9  Priya   80.000000  84.000000        0   92.000000

In [79]:
# Handle inconsistencies

# Marks and attendance should be between 0 and 100

df['Maths'] = df['Maths'].clip(0, 100)

df['English'] = df['English'].clip(0, 100)

df['Attendance'] = df['Attendance'].clip(0, 100)

print("Dataset after removing inconsistencies:\n")

df

Dataset after removing inconsistencies:

    Name       Maths    Science  English  Attendance
0   Amit   85.000000  80.000000       78   90.000000
1   Riya   90.000000  85.000000       88   95.000000
2  Karan   79.222222  70.000000       65   85.000000
3  Sneha   45.000000  78.888889       50   60.000000
4  Rahul  100.000000  95.000000       98  100.000000
5  Pooja   78.000000  76.000000       74   80.000000
6  Vikas   88.000000  89.000000       90   88.000000
7   Neha   92.000000  91.000000       93   83.888889
8  Arjun   35.000000  40.000000       42   55.000000
9  Priya   80.000000  84.000000        0   92.000000

In [81]:
# Detect outliers using IQR method

Q1 = df['Maths'].quantile(0.25)

Q3 = df['Maths'].quantile(0.75)

IQR = Q3 - Q1

print("Q1 =", Q1)
print("Q3 =", Q3)
print("IQR =", IQR)

Q1 = 78.30555555555556
Q3 = 89.5
IQR = 11.194444444444443

In [83]:
# Define lower and upper limits

lower_limit = Q1 - 1.5 * IQR

upper_limit = Q3 + 1.5 * IQR

print("Lower Limit =", lower_limit)
print("Upper Limit =", upper_limit)

Lower Limit = 61.51388888888889
Upper Limit = 106.29166666666666

In [85]:
# Remove outliers

df_no_outliers = df[(df['Maths'] >= lower_limit) &
                    (df['Maths'] <= upper_limit)]

print("Dataset after removing outliers:\n")

df_no_outliers

Dataset after removing outliers:

    Name       Maths  Science  English  Attendance
0   Amit   85.000000     80.0       78   90.000000
1   Riya   90.000000     85.0       88   95.000000
2  Karan   79.222222     70.0       65   85.000000
4  Rahul  100.000000     95.0       98  100.000000
5  Pooja   78.000000     76.0       74   80.000000
6  Vikas   88.000000     89.0       90   88.000000
7   Neha   92.000000     91.0       93   83.888889
9  Priya   80.000000     84.0        0   92.000000

In [87]:
# Apply log transformation

df_no_outliers['Log_Maths'] = np.log(df_no_outliers['Maths'])

print("Dataset after Log Transformation:\n")

df_no_outliers[['Maths', 'Log_Maths']]

Dataset after Log Transformation:

C:\Users\Prajwal\AppData\Local\Temp\ipykernel_48152\1505001492.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_no_outliers['Log_Maths'] = np.log(df_no_outliers['Maths'])

        Maths  Log_Maths
0   85.000000   4.442651
1   90.000000   4.499810
2   79.222222   4.372257
4  100.000000   4.605170
5   78.000000   4.356709
6   88.000000   4.477337
7   92.000000   4.521789
9   80.000000   4.382027