# DirtyData

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("./datasets/dirtydata.csv")

In [24]:
df.head() # get top 5 entries

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [28]:
df.shape # get the size of the data in the format of  (rows, columns)

(32, 5)

In [30]:
df.tail() # to get the buttom 5 entries

    Duration          Date  Pulse  Maxpulse  Calories
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132    -280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [32]:
df.describe() # get the mean and other information related to the dataset

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  266.013333
std     70.039591    7.832933   12.998759  164.876415
min     30.000000   90.000000  101.000000 -300.000000
25%     60.000000  100.000000  120.000000  247.000000
50%     60.000000  102.500000  127.500000  282.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

In [34]:
df.dtypes #to get the data types of the columns in the dataset

Duration      int64
Date         object
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

In [66]:
df["Calories"] = df["Calories"].abs()
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130    409.10
1         60  '2020/12/02'    117       145    479.00
2         60  '2020/12/03'    103       135    340.00
3         45  '2020/12/04'    109       175    282.40
4         45  '2020/12/05'    117       148    406.00
5         60  '2020/12/06'    102       127    300.00
6         60  '2020/12/07'    110       136    374.00
7        450  '2020/12/08'    104       134    253.30
8         30  '2020/12/09'    109       133    195.10
9         60  '2020/12/10'     98       124    269.00
10        60  '2020/12/11'    103       147    329.30
11        60  '2020/12/12'    100       120    250.70
12        60  '2020/12/12'    100       120    250.70
13        60  '2020/12/13'    106       128    345.30
14        60  '2020/12/14'    104       132    379.30
15        60  '2020/12/15'     98       123    275.00
16        60  '2020/12/16'     98       120    215.20
17        60  '2020/12/17'    100       120    300.00
18        45  '2020/12/18'     90       112    304.68
19        60  '2020/12/19'    103       123    323.00
20        45  '2020/12/20'     97       125    243.00
21        60  '2020/12/21'    108       131    364.20
23        60  '2020/12/23'    130       101    300.00
24        45  '2020/12/24'    105       132    246.00
25        60  '2020/12/25'    102       126    334.50
26        60      20201226    100       120    250.00
27        60  '2020/12/27'     92       118    241.00
28        60  '2020/12/28'    103       132    304.68
29        60  '2020/12/29'    100       132    280.00
30        60  '2020/12/30'    102       129    380.30
31        60  '2020/12/31'     92       115    243.00

In [68]:
df.isnull().sum()

Duration    0
Date        0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

In [70]:
x = df["Calories"].mean()

In [72]:
x

305.41161290322583

In [74]:
df["Calories"] = df["Calories"].fillna(x)

In [76]:
df.isnull().sum()

Duration    0
Date        0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

In [78]:
df.dropna(subset=['Date'], inplace = True)

In [80]:
df.shape

(31, 5)

In [82]:
df.isnull().sum()

Duration    0
Date        0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

In [84]:
df.dtypes

Duration      int64
Date         object
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

In [86]:
df['Calories'] = df["Calories"].astype(int)

In [90]:
df.dtypes

Duration     int64
Date        object
Pulse        int64
Maxpulse     int64
Calories     int32
dtype: object

In [92]:
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130       409
1        60  '2020/12/02'    117       145       479
2        60  '2020/12/03'    103       135       340
3        45  '2020/12/04'    109       175       282
4        45  '2020/12/05'    117       148       406

In [94]:
df.loc[2,"Duration"] = 50

In [96]:
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130       409
1        60  '2020/12/02'    117       145       479
2        50  '2020/12/03'    103       135       340
3        45  '2020/12/04'    109       175       282
4        45  '2020/12/05'    117       148       406

In [98]:
df.duplicated().sum()

1

In [100]:
df.shape

(31, 5)

In [102]:
df.drop_duplicates(inplace=True)

In [104]:
df.shape

(30, 5)

In [108]:
df.duplicated().sum()

0

# NBA

In [226]:
data = pd.read_csv("./datasets/nba.csv")

In [228]:
data.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [230]:
data.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [232]:
data.shape

(458, 9)

In [234]:
data["Position"].value_counts()

Position
SG    102
PF    100
PG     92
SF     85
C      78
Name: count, dtype: int64

can use label encoding for this

In [236]:
data["Position"].replace(['SG','PF','PG','SF','C'], [0,1,2,3,4], inplace = True)

C:\Users\Prajwal\AppData\Local\Temp\ipykernel_36276\3473907140.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Position"].replace(['SG','PF','PG','SF','C'], [0,1,2,3,4], inplace = True)
C:\Users\Prajwal\AppData\Local\Temp\ipykernel_36276\3473907140.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["Position"].replace(['SG','PF','PG','SF','C'], [0,1,2,3,4], inplace = True)

In [238]:
data.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,2.0,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,3.0,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,0.0,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,0.0,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,1.0,29.0,6-10,231.0,NaN,5000000.0

## Label Encoding

In [369]:
import pandas as pd

In [371]:
from sklearn import preprocessing

In [373]:
data_nba = pd.read_csv("./datasets/nba.csv")

In [375]:
data_nba["Position"].unique()

array(['PG', 'SF', 'SG', 'PF', 'C', nan], dtype=object)

In [377]:
label_encoder = preprocessing.LabelEncoder()

In [379]:
data_nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [381]:
data_nba.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [383]:
data_nba["Position"] = label_encoder.fit_transform(data_nba["Position"])

In [385]:
data_nba["Position"].unique()

array([2, 3, 4, 1, 0, 5])

In [387]:
data_nba.dtypes

Name         object
Team         object
Number      float64
Position      int32
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

GPT for query

In [391]:
data_nba["Salary"] = data_nba["Salary"].fillna(data_nba.groupby("Position")["Salary"].transform('mean'))

In [389]:
data_nba.isnull().sum()

Name         1
Team         1
Number       1
Position     0
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [393]:
data_nba.isnull().sum()

Name         1
Team         1
Number       1
Position     0
Age          1
Height       1
Weight       1
College     85
Salary       1
dtype: int64

In [395]:
category = pd.cut(data_nba.Age, bins = [19,25,30,35,45], labels = ['A','B','C','D'])

In [397]:
data_nba.insert(5, "Age_Group", category)

In [399]:
data_nba.head()

,Name,Team,Number,Position,Age,Age_Group,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,2,25.0,A,6-2,180.0,Texas,7.730337e+06
1,Jae Crowder,Boston Celtics,99.0,3,25.0,A,6-6,235.0,Marquette,6.796117e+06
2,John Holland,Boston Celtics,30.0,4,27.0,B,6-5,205.0,Boston University,4.009861e+06
3,R.J. Hunter,Boston Celtics,28.0,4,22.0,A,6-5,185.0,Georgia State,1.148640e+06
4,Jonas Jerebko,Boston Celtics,8.0,1,29.0,B,6-10,231.0,NaN,5.000000e+06

In [401]:
data_nba.isnull().sum()

Name          1
Team          1
Number        1
Position      0
Age           1
Age_Group     3
Height        1
Weight        1
College      85
Salary        1
dtype: int64

In [403]:
data_nba= data_nba.drop(columns= ["College"])

In [405]:
data_nba.isnull().sum()

Name         1
Team         1
Number       1
Position     0
Age          1
Age_Group    3
Height       1
Weight       1
Salary       1
dtype: int64

In [407]:
data_nba["Age_Group"].value_counts()

Age_Group
A    197
B    167
C     68
D     23
Name: count, dtype: int64

In [409]:
data_nba["Age_Group"].unique()

['A', 'B', 'C', 'D', NaN]
Categories (4, object): ['A' < 'B' < 'C' < 'D']

In [411]:
data_nba["Age_Group"]= data_nba["Age_Group"].fillna('A')

In [421]:
data_nba.isnull().sum()

Name         1
Team         1
Number       1
Position     0
Age          1
Age_Group    0
Height       1
Weight       1
Salary       1
dtype: int64

In [415]:
data_nba.shape

(458, 9)

In [417]:
data_nba = data_nba.dropna(axis=1, how='all')

In [419]:
data_nba.shape

(458, 9)

In [423]:
data_nba.to_csv('NBA-Data.csv')